export enum ActionType {
  // Events
  EVENTS_GET = 'EVENTS/GET_ALL',
  EVENTS_GET_HOLIDAYS = 'EVENTS/GET_ALL_HOLIDAYS',
  EVENTS_DELETE = 'EVENTS/DELETE',
  EVENTS_UPDATE = 'EVENTS/UPDATE',
  EVENTS_UPDATE_SEQUENCE_NUM = 'EVENTS/UPDATE_SEQUENCE_NUM',
  EVENTS_CREATE = 'EVENTS/CREATE',
  EVENTS_GET_BY_ID = 'EVENTS/GET_BY_ID',
  EVENTS_DOWNLOAD = 'EVENTS/DOWNLOAD',
  EVENTS_UPLOAD = 'EVENTS/UPLOAD',
  // labels DB
  EVENTS_LABELS_GET = 'LABELS/GET_ALL',
  EVENTS_LABELS_UPDATE = 'LABELS/UPDATE',
  EVENTS_LABELS_CREATE = 'LABELS/CREATE',
  //Current date
  CURRENT_DATE_UPDATE = 'CURRENT_DATE/UPDATE',
  //Create user DB
  USER_CREATE = 'USER/CREATE',
}
